Repository eclipse-ee4j/soteria, pull requests merged in 2023-06, with the labels that each got.

#357 Prevent OpenIdIdentityStore from being enabled by default.
  impl/src/main/java/org/glassfish/soteria/mechanisms/openid/OpenIdIdentityStore.java
Labels: bug

#358 Add preconditions to determine callback for OpenID Connect.
  impl/src/main/java/org/glassfish/soteria/mechanisms/OpenIdAuthenticationMechanism.java
Labels: enhancement

#360 Update some minor versions in pom and remove overriding versions
  impl/pom.xml
  pom.xml
Labels: dependencies

#344 Do not require a caller principal obtained from EJB to be assignable from CallerPrincipal
  impl/src/main/java/org/glassfish/soteria/authorization/spi/impl/SubjectParser.java
Labels: bug

#361 Do not require a caller principal obtained from EJB to be assignable from CallerPrincipal
  impl/src/main/java/org/glassfish/soteria/authorization/spi/impl/SubjectParser.java
Labels: bug
